### ISSUE TITLE
Declarative Pipeline - Support CustomPipelineTemplate

### ISSUE THREAD

**Issue by sujikann** [manheim/terraform-pipeline#219] opened 2020-05-08 15:04 UTC
### Overview

The terraform-pipeline supports setting up a Declarative pipeline. Declarative pipelines give us the advantage of restarting pipeline from a stage from a previous run. "Restart from Stage" requires the stash artifact to be available to use in a subsequent stage.
This issue can be resolved by using a CustomPipelineTemplate. However, Jenkins throws an error when we use a CustomPipelineTemplate. 
Version
Pipeline 2.6 version on Jenkins 
terraform-pipeline 5.6

### Error
groovy.lang.MissingPropertyException: No such property: none for class: CustomPipelineTemplate

@Library(['terraform-pipeline@v5.6', 'terraform-pipeline-customizations']) _
```
Jenkinsfile.init(this)
Jenkinsfile.declarative = true
Jenkinsfile.pipelineTemplate = this.CustomPipelineTemplate
```
vars/CustomPipelineTemplate.groovy
```
pipeline {
     agent none

     options { preserveStashes() }
     stages {
         stage('Validate') {
             steps {
                 script {
                     validate.build()
                 }
             }
         }
 
         stage('Build Artifact') {
             steps {
                 script {
                     buildArtifact.build()
                 }
             }
         }
  }
```

**Comment by dkolb** [comment] 2020-05-09 16:45
Per the [README.md](https://github.com/manheim/terraform-pipeline#scripted-vs-declarative-pipelines-restart-from-stage), `vars/CustomPipelineTemplate.groovy` should define a method `call(stages)` and then you use `((Stage)stages.getAt(index)).build()`.

**Comment by sujikann** [comment] 2020-05-11 21:12
I tried this but it didnt work. The pipeline gives an error saying 
groovy.lang.MissingPropertyException: No such property: any for class: CustomPipelineTemplate.

**Comment by kmanning** [comment] 2020-05-29 20:08
Talked with sujikann, and confirmed the problem.

1.  Follow the README and create a custom template: 
```
// var/CustomPipelineTemplate.groovy
def call(args) {
    pipeline {
        agent none

        stages {
...
```
2. Create a declarative pipeline, and use your template:
```
Jenkinsfile.init(this)
Jenkinsfile.declarative = true
Jenkinsfile.pipelineTemplate = this.CustomPipelineTemplate
```
**Expected:** you get a declarative pipeline using the code provided by your template
**Actual:** you get the error `groovy.lang.MissingPropertyException: No such property: any for class: CustomPipelineTemplate.`

**Comment by kmanning** [comment] 2020-05-29 20:10
Looks like there's a defect in the README itself.  For some reason, naming your variable `stages` causes some sort of problem.  If you rename the variable to `args`, the problem goes away.

Example:
```
// var/CustomPipelineTemplate.groovy
def call(args) {
    pipeline {
        agent none

        stages {
...
```
The docs should be fixed, so that if you copy/paste the example code, it works.

**Comment by sujikann** [comment] 2020-05-29 20:21
> Looks like there's a defect in the README itself. For some reason, naming your variable `stages` causes some sort of problem. If you rename the variable to `args`, the problem goes away.
> 
> Example:
> 
> ```
> // var/CustomPipelineTemplate.groovy
> def call(args) {
>     pipeline {
>         agent none
> 
>         stages {
> ...
> ```
> 
> The docs should be fixed, so that if you copy/paste the example code, it works.

**Comment by kmanning** [comment] 2020-05-29 20:31
Gonna reopen the issue, only because the documentation is incorrect and should be fixed, to prevent this problem/confusion in the future.

**Closed** 2020-07-07 19:53 UTC
Labels: bug, documentation
